// rm-fence-web-app/src/app/views/home/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';
import { WindowRefService } from '@shared/services/window-ref/window-ref.service';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss'],
})
export class FooterComponent implements OnInit {
  constructor(private windowRefService: WindowRefService) {}

  ngOnInit() {}

  call() {
    this.windowRefService.nativeWindow().open('tel:+4402365758');
  }
}

<footer id="footer-section" class="home-footer">
  <section class="home-footer-top">
    <div class="container">
      <div fxLayout="row" fxLayout.lt-md="column" fxLayoutWrap="nowrap">
        <div fxFlex="40" class="footer-box">
          <h4 class="footer-box-title"><b>About Us</b></h4>
          <p>
            We offer high quality fencing solutions for your home or business.
            Our fences are affordable and add to the security and elegance of
            your property. We keep our prices low by performing the work
            ourselves, and not hiring any subcontractors.
          </p>
          <p>
            We are locally owned and operated and serve Columbia Station, OH and
            the surrounding area including Cuyahoga, Lorain, and Medina
            counties.
          </p>
          <!--
            No Subtracting
            All Employees are Hourly
            Owner Operated
            Quality & Affordable
            We Use All American Made Material -->

          <button mat-raised-button color="accent" (click)="call()">
            <mat-icon>phone</mat-icon>
            Contact Us
          </button>
        </div>
        <div fxFlex="30" class="footer-box">
          <h4 class="footer-box-title"><b>Contact</b></h4>
          <mat-list>
            <mat-list-item>
              <mat-icon mat-list-icon color="accent">phone</mat-icon>
              <h5 matLine><b>Phone</b></h5>
              <p matLine><a href="tel:+4402365758">(440) 236-5758</a></p>
            </mat-list-item>
            <mat-list-item>
              <mat-icon mat-list-icon color="accent">email</mat-icon>
              <h5 matLine><b>Email</b></h5>
              <p matLine class="force-break-wrap-text">
                <a href="mailto:rmfence2006@gmail.com">rmfence2006@gmail.com</a>
              </p>
            </mat-list-item>
          </mat-list>
        </div>

        <div fxFlex="30" class="footer-box service-area-image"  fxLayoutAlign="center">
            <img src="assets/images/greater-cleveland-service-area.png" alt="">
        </div>

      </div>
    </div>
  </section>
</footer>

// rm-fence-svelte-web-app/src/components/Footer.svelte
<script>
	import { Icon,Label } from '@smui/button';
	import Button from '@smui/button/src/Button.svelte';
	import List,{ Graphic,Item,PrimaryText,SecondaryText,Text } from '@smui/list';

	const src = '/greater-cleveland-service-area.png';
</script>

<footer id="footer-section" class="home-footer">
	<section class="home-footer-top">
		<div class="container my-0 mx-auto px-4 max-w-6xl">
			<!-- fxLayout="row" fxLayout.lt-md="column" fxLayoutWrap="nowrap" -->
			<div class="flex flex-col md:flex-row flex-nowrap">
				<div class="footer-box md:w-3/5">
					<h4 class="footer-box-title"><b>About Us</b></h4>
					<p class="text-sm mb-2">
						We offer high quality fencing solutions for your home or business. Our fences are
						affordable and add to the security and elegance of your property. We keep our prices low
						by performing the work ourselves, and not hiring any subcontractors.
					</p>
					<p class="text-sm mb-4">
						We are locally owned and operated and serve Columbia Station, OH and the surrounding
						area including Cuyahoga, Lorain, and Medina counties.
					</p>

					<Button href="tel:+4402365758" target="_blank" variant="raised">
						<Icon class="material-icons">phone</Icon>
						<Label>Contact Us</Label>
					</Button>
				</div>
				<div class="md:w-1/3 footer-box">
					<h4 class="footer-box-title"><b>Contact</b></h4>

					<List class="" twoLine>
						<Item>
							<a href="tel:+4402365758" target="_blank" class="absolute w-full h-full" >&#32</a>
							<Graphic class="material-icons text-yellow-500">phone</Graphic>

							<Text>
								<PrimaryText class="text-white">Phone</PrimaryText>
								<SecondaryText class="text-white break-normal">(440) 236-5758</SecondaryText>
							</Text>
						</Item>
						<Item>
							<a href="mailto:rmfence2006@gmail.com" target="_blank" class="absolute w-full h-full" >&#32</a>
							<Graphic class="material-icons text-yellow-500">email</Graphic>

							<Text>
								<PrimaryText class="text-white">Email</PrimaryText>
								<SecondaryText class="text-white break-normal">rmfence2006@gmail.com</SecondaryText>
							</Text>
						</Item>
					</List>
				</div>

				<!-- fxLayoutAlign="center" -->
				<div class="md:w-1/3	footer-box service-area-image">
					<img {src} alt="service area" />
				</div>
			</div>
		</div>
	</section>
</footer>

<style lang="scss">
	.home-footer-top {
		background-color: #212121;
		color: #ffffff !important;
	}

	.footer-box {
		padding: 30px;
		box-shadow: 3px 0px 4px rgba(0, 0, 0, 0.2);
	}
	.footer-box:first-child {
		padding-left: 0;
	}
	.footer-box-title {
		position: relative;
		margin: 0 0 24px;
		padding-bottom: 12px;
	}   

	@media (max-width: 959px) {
		.footer-box:first-child {
			padding-left: 30px;
		}
		.footer-box {
			box-shadow: 0px 3px 2px rgba(0, 0, 0, 0.2);
		}
	}
</style>
